export default {
    CLIENT_ID: 'w7phwf9eQ48nTFOBZ2pSHXgVXg8BVLErJ1U9iBag',
    CLIENT_SECRET: 'RTHmmXBVG8RykQRLe1ZRgNspMgTZdCXBbHsAKHVaZSyn4pNK2TwA0GjEIWowHjUDHQI8JMmVFZwDlgEikFTlICDKBIwFKwxGXP9d91tuPWo3y1DWxqGcXl9dQjZ4XQvm'
}