# Generated by Django 5.1.7 on 2025-03-28 14:10

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='job',
            name='id_admin',
        ),
        migrations.RemoveField(
            model_name='job',
            name='id_employer',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='job',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dx6brcofe/image/upload/v1736245841/woxspsofipalpoz8r4aj.jpg', max_length=255),
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('descriptions', models.TextField()),
                ('requirements', models.TextField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_type', models.IntegerField(choices=[(1, 'Full Time'), (2, 'Part Time'), (3, 'Constract'), (4, 'Internship'), (5, 'Freelance'), (6, 'Temporary'), (7, 'Remote Work'), (8, 'Order')], default=1)),
                ('quantity', models.IntegerField()),
                ('id_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_jobs', to=settings.AUTH_USER_MODEL)),
                ('id_employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_jobs', to=settings.AUTH_USER_MODEL)),
                ('id_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='apply',
            name='id_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobposting'),
        ),
        migrations.AlterField(
            model_name='result',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='job.jobposting'),
        ),
    ]
