# Generated by Django 5.1.7 on 2025-03-29 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='name',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='id_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.city'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='id_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.district'),
        ),
        migrations.DeleteModel(
            name='UserInformation',
        ),
    ]
