# Generated by Django 5.1.7 on 2025-03-29 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='id_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.city'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='id_district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.district'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Applicant'), (2, 'Employer'), (3, 'Admin')], default=1),
        ),
    ]
