# Generated by Django 5.1.7 on 2025-03-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_jobposting_descriptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='quantity',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
