# Generated by Django 5.1.7 on 2025-03-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_jobposting_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
