# Generated by Django 5.1.7 on 2025-03-29 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_remove_jobposting_id_admin_result_id_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='id_cv',
            new_name='cv',
        ),
        migrations.RenameField(
            model_name='apply',
            old_name='id_job',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='id_applicant',
            new_name='applicant',
        ),
        migrations.RenameField(
            model_name='jobposting',
            old_name='id_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='jobposting',
            old_name='id_district',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='jobposting',
            old_name='id_employer',
            new_name='employer',
        ),
        migrations.RenameField(
            model_name='jobposting',
            old_name='id_job',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='id_admin',
            new_name='admin',
        ),
    ]
