# Generated by Django 5.1.7 on 2025-03-29 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_rename_id_cv_apply_cv_rename_id_job_apply_job_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='id_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='id_user',
            new_name='user',
        ),
    ]
