# Generated by Django 5.1.7 on 2025-03-29 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_rename_id_city_district_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='note',
        ),
    ]
