# Generated by Django 5.1.7 on 2025-03-31 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_applicantcertificate_alter_phone_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='phone',
            new_name='value',
        ),
    ]
