# Generated by Django 5.1.7 on 2025-03-31 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_rename_phone_phone_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicanteduactionlevel',
            name='cetificate',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='JobSearchCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('job_type', models.IntegerField(choices=[(1, 'Full Time'), (2, 'Part Time'), (3, 'Constract'), (4, 'Internship'), (5, 'Freelance'), (6, 'Temporary'), (7, 'Remote Work'), (8, 'Order')], default=1)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.city')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.district')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ApplicantCertificate',
        ),
    ]
