# Generated by Django 5.1.7 on 2025-04-01 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_alter_applicanteduactionlevel_cetificate_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicantEduactionLevel',
            new_name='EduactionLevel',
        ),
        migrations.RenameModel(
            old_name='ApplicantExperience',
            new_name='Experience',
        ),
        migrations.RenameModel(
            old_name='ApplicantSkill',
            new_name='Skill',
        ),
    ]
