# Generated by Django 5.1.7 on 2025-04-01 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_rename_applicanteduactionlevel_eduactionlevel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eduactionlevel',
            old_name='cetificate',
            new_name='certificate',
        ),
    ]
