# Generated by Django 5.1.7 on 2025-04-01 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_rename_cetificate_eduactionlevel_certificate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eduactionlevel',
            old_name='descriptions',
            new_name='description',
        ),
    ]
