# Generated by Django 5.1.7 on 2025-04-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0020_rename_descriptions_eduactionlevel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='value',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
