# Generated by Django 5.1.7 on 2025-04-01 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0021_skill_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='desciptions',
            new_name='desciption',
        ),
    ]
