# Generated by Django 5.1.7 on 2025-04-01 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0022_rename_desciptions_experience_desciption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='desciption',
            new_name='description',
        ),
    ]
