# Generated by Django 5.1.7 on 2025-04-01 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0023_rename_desciption_experience_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsearchcriteria',
            name='id',
        ),
        migrations.AlterField(
            model_name='jobsearchcriteria',
            name='applicant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
