# Generated by Django 5.1.7 on 2025-04-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0024_remove_jobsearchcriteria_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='job',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='jobsearchcriteria',
            name='job',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='experience',
            name='job',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
