# Generated by Django 5.1.7 on 2025-04-06 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0025_alter_jobposting_job_alter_jobsearchcriteria_job_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='city',
        ),
        migrations.RemoveField(
            model_name='jobsearchcriteria',
            name='city',
        ),
    ]
