# Generated by Django 5.1.7 on 2025-04-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0026_remove_jobposting_city_remove_jobsearchcriteria_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EduactionLevel',
            new_name='EducationLevel',
        ),
    ]
