# Generated by Django 5.1.7 on 2025-04-08 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0027_rename_eduactionlevel_educationlevel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
