# Generated by Django 5.1.7 on 2025-04-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0028_rename_descriptions_jobposting_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='address',
            field=models.CharField(default='gg', max_length=60),
            preserve_default=False,
        ),
    ]
