# Generated by Django 5.1.7 on 2025-04-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0029_jobposting_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
