# Generated by Django 5.1.7 on 2025-04-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0030_apply_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='seen',
        ),
        migrations.AlterField(
            model_name='apply',
            name='apply_status',
            field=models.IntegerField(choices=[(1, 'Sent'), (2, 'Seen'), (3, 'Interviewing'), (4, 'Passed'), (5, 'Failed'), (6, 'Cancel')], default=1),
        ),
    ]
