# Generated by Django 5.1.7 on 2025-04-09 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0031_remove_apply_seen_alter_apply_apply_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='job',
            new_name='job_posting',
        ),
    ]
