# Generated by Django 5.1.7 on 2025-04-09 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0032_rename_job_apply_job_posting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='expired_date',
        ),
    ]
