# Generated by Django 5.1.7 on 2025-04-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0034_rename_id_result_job_posting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='message',
            field=models.TextField(),
        ),
    ]
