# Generated by Django 5.1.7 on 2025-04-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0035_alter_apply_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='message',
            field=models.TextField(max_length=60),
        ),
    ]
