# Generated by Django 5.1.7 on 2025-04-12 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0036_alter_apply_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyDateAndMessage',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('apply', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='job.apply')),
                ('message', models.TextField()),
                ('interviewing_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='apply',
            name='interviewing_date',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='message',
        ),
    ]
