# Generated by Django 5.1.7 on 2025-04-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0037_applydateandmessage_remove_apply_interviewing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applydateandmessage',
            name='interviewing_date',
            field=models.DateTimeField(null=True),
        ),
    ]
