# Generated by Django 5.1.7 on 2025-04-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0038_alter_applydateandmessage_interviewing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applydateandmessage',
            name='interviewing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
