# Generated by Django 5.1.7 on 2025-04-18 15:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0041_alter_chatgroup_unique_together_expopushtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='woxspsofipalpoz8r4aj', max_length=255, verbose_name='image'),
        ),
    ]
