# Generated by Django 5.1.7 on 2025-04-21 10:19

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0045_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.CreateModel(
            name='VideoCallRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=30)),
                ('apply_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.apply')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ChatGroup',
        ),
    ]
