# Generated by Django 5.1.7 on 2025-05-05 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0046_alter_user_avatar_videocallroom_delete_chatgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocallroom',
            name='id',
        ),
        migrations.AlterField(
            model_name='videocallroom',
            name='apply_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='job.apply'),
        ),
    ]
