# Generated by Django 5.1.7 on 2025-06-03 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0047_remove_videocallroom_id_alter_videocallroom_apply_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoCallRoom',
        ),
    ]
